### ISSUE TITLE
Group feature

### ISSUE THREAD

**Issue by ChristophHirche** [scirate/scirate#347] opened 2018-02-12 13:40 UTC
I would like to suggest a feature, that might be beneficial for many research groups: 

Could we have a group feature where people can assign themselves to a group, with the possibility of filtering the start page in order to only see scites made from this group of people (/your own group). 

The scenario I have in mind is e.g. giving a quick overview over the scites from the own group in a group meeting (without additionally having to externally collect the papers). 
It seems like a simple tag and filter system might do the job, although I am no expert... but I think it would simplify group meetings and encourage more people in those groups to use SciRate.

**Comment by silky** [comment] 2018-02-24 07:08
here's a related issue from earlier: https://github.com/scirate/scirate/issues/136

**Comment by silky** [comment] 2020-10-01 20:47
duplicate of #366

**Closed by silky** 2020-10-01 20:47 UTC
